kitchen/urls.py
from django.urls import path

from kitchen.views import (
    IndexView,
    IngredientListView,
    IngredientCreateView,
    IngredientDeleteView,
    DishTypeListView,
    DishTypeCreateView,
    DishTypeDeleteView,
    DishListView,
    DishDetailView,
    DishCreateView,
    DishUpdateView,
    DishDeleteView,
    DishTypeUpdateView,
    CookListView,
    CookDetailView,
    CookCreateView,
    CookUpdateView,
    ToggleAssignToDish,
    CookDeleteView,
)

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("ingredient/", IngredientListView.as_view(), name="ingredient-list"),
    path("ingredient/create/", IngredientCreateView.as_view(), name="ingredient-create"),
    path("ingredient/<int:pk>/delete/", IngredientDeleteView.as_view(), name="ingredient-delete"),
    path("dish_type/", DishTypeListView.as_view(), name="dish-type-list"),
    path("dish_type/create/", DishTypeCreateView.as_view(), name="dish-type-create"),
    path("dish_type/<int:pk>/update/", DishTypeUpdateView.as_view(), name="dish-type-update"),
    path("dish_type/<int:pk>/delete", DishTypeDeleteView.as_view(), name="dish-type-delete"),
    path("dish/", DishListView.as_view(), name="dish-list"),
    path("dish/<int:pk>/", DishDetailView.as_view(), name="dish-detail"),
    path("dish/create/", DishCreateView.as_view(), name="dish-create"),
    path("dish/<int:pk>/update/", DishUpdateView.as_view(), name="dish-update"),
    path("dish/<int:pk>/delete/", DishDeleteView.as_view(), name="dish-delete"),
    path("dishes/<int:pk>/toggle-assign/", ToggleAssignToDish.as_view(), name="toggle-dish-assign",),
    path("cook/", CookListView.as_view(), name="cook-list"),
    path("cook/<int:pk>/", CookDetailView.as_view(), name="cook-detail"),
    path("cook/create/", CookCreateView.as_view(), name="cook-create"),
    path("cook/<int:pk>/update/", CookUpdateView.as_view(), name="cook-update"),
    path("cook/<int:pk>/delete/", CookDeleteView.as_view(), name="cook-delete"),
]

app_name = "kitchen"

restaurant/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("kitchen.urls", namespace="kitchen")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/includes/footer.html
  <footer class="footer">
    <hr class="horizontal dark mb-5 mt-0">
    <div class="container">
      <div class=" row">
        <div class="col-md-3 mb-4 ms-auto">
          <div>
            <h6 class="text-gradient text-primary font-weight-bolder">Restaurant Kitchen Service</h6>
          </div>
          <div>
            <h6 class="mt-3 mb-2 opacity-8">Social</h6>
            <ul class="d-flex flex-row ms-n3 nav">
              <li class="nav-item">
                <a class="nav-link pe-1">
                  <i class="fab fa-facebook text-lg opacity-8"></i>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link pe-1">
                  <i class="fab fa-twitter text-lg opacity-8"></i>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link pe-1">
                  <i class="fab fa-dribbble text-lg opacity-8"></i>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link pe-1">
                  <i class="fab fa-github text-lg opacity-8"></i>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link pe-1">
                  <i class="fab fa-youtube text-lg opacity-8"></i>
                </a>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-md-2 col-sm-6 col-6 mb-4">
          <div>
            <h6 class="text-gradient text-primary text-sm">Company</h6>
            <ul class="flex-column ms-n3 nav">
              <li class="nav-item">
                <a class="nav-link">
                  About Us
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link">
                  Freebies
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link">
                  Premium Tools
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link">
                  Blog
                </a>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-md-2 col-sm-6 col-6 mb-4">
          <div>
            <h6 class="text-gradient text-primary text-sm">Resources</h6>
            <ul class="flex-column ms-n3 nav">
              <li class="nav-item">
                <a class="nav-link">
                  Illustrations
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link">
                  Bits & Snippets
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link">
                  Affiliate Program
                </a>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-md-2 col-sm-6 col-6 mb-4">
          <div>
            <h6 class="text-gradient text-primary text-sm">Help & Support</h6>
            <ul class="flex-column ms-n3 nav">
              <li class="nav-item">
                <a class="nav-link">
                  Contact Us
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link">
                  Knowledge Center
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link">
                  Custom Development
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link">
                  Sponsorships
                </a>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-md-2 col-sm-6 col-6 mb-4 me-auto">
          <div>
            <h6 class="text-gradient text-primary text-sm">Legal</h6>
            <ul class="flex-column ms-n3 nav">
              <li class="nav-item">
                <a class="nav-link">
                  Terms & Conditions
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link">
                  Privacy Policy
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link">
                  Licenses (EULA)
                </a>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-12">
          <div class="text-center">
            <p class="my-4 text-sm">
              Restaurant Kitchen Service by &copy; Mykhailo Benzel
            </p>
          </div>
        </div>
      </div>
    </div>
  </footer>

templates/includes/navigation.html
  <div class="container position-sticky z-index-sticky top-0">
    <div class="row">
      <div class="col-12">
        <nav class="navbar navbar-expand-lg  blur blur-rounded top-0 z-index-fixed shadow position-absolute my-3 py-2 start-0 end-0 mx-4">
          <div class="container-fluid">
            <a class="navbar-brand font-weight-bolder ms-sm-3" 
               href="/" rel="tooltip" title="Designed and Coded by Creative Tim" data-placement="bottom">
              Restaurant Kitchen Service
            </a>
            <button class="navbar-toggler shadow-none ms-2" type="button" data-bs-toggle="collapse" data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon mt-2">
                <span class="navbar-toggler-bar bar1"></span>
                <span class="navbar-toggler-bar bar2"></span>
                <span class="navbar-toggler-bar bar3"></span>
              </span>
            </button>
            <div class="collapse navbar-collapse pt-3 pb-2 py-lg-0" id="navigation">
              <ul class="navbar-nav navbar-nav-hover ms-lg-12 ps-lg-5 w-100">
                <li class="nav-item dropdown dropdown-hover mx-2">
                  <a class="nav-link ps-2 d-flex justify-content-between cursor-pointer align-items-center font-weight-bold" href="{% url 'kitchen:dish-list' %}">
                    Dishes
                  </a>
                </li>
                <li class="nav-item dropdown dropdown-hover mx-2">
                  <a class="nav-link ps-2 d-flex justify-content-between cursor-pointer align-items-center font-weight-bold" href="{% url 'kitchen:dish-type-list' %}">
                    Dishes type
                  </a>
                </li>
                <li class="nav-item dropdown dropdown-hover mx-2">
                  <a class="nav-link ps-2 d-flex justify-content-between cursor-pointer align-items-center font-weight-bold" href="{% url 'kitchen:ingredient-list' %}">
                    Ingredients
                  </a>
                </li>
                <li class="nav-item dropdown dropdown-hover mx-2">
                  <a class="nav-link ps-2 d-flex justify-content-between cursor-pointer align-items-center font-weight-bold" href="{% url 'kitchen:cook-list' %}">
                    Cooks
                  </a>
                </li>
                <li class="nav-item ms-lg-auto">
                  <a class="nav-link nav-link-icon me-2" href="{% url 'logout' %}">
                    <i class="fa fa-sign-out me-1"></i>
                    <p class="d-inline text-sm z-index-1 font-weight-bold" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Logout">Logout</p>
                  </a>
                </li>
                <li class="nav-item my-auto ms-3 ms-lg-0">
                  <a href="https://github.com/Mykhailo-Benzel/restaurant-kitchen-service"
                     target="_blank"
                     class="btn btn-sm  bg-gradient-primary btn-round mb-0 me-1 mt-2 mt-md-0">Project on github</a>
                </li>
                <li class="nav-item my-auto ms-3 ms-lg-0">
                  {% if user.is_authenticated %}
                     <a href="{% url 'kitchen:cook-detail' user.id%}"
                     class="mx-3"><img src="/static/assets/img/cook-icon-5.png" alt=""></a>
                  {% else %}
                     <a href=""
                     class="mx-3"><img src="/static/assets/img/cook-icon-5.png" alt=""></a>
                  {% endif %}
                </li>
              </ul>
            </div>
          </div>
        </nav>
        <!-- End Navbar -->
      </div>
    </div>
  </div>

templates/includes/pagination.html
{% load query_transform %}

{% if is_paginated %}
  <ul class="pagination pagination-lg justify-content-center pb-3">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.previous_page_number %}" class="page-link shadow-lg">prev</a>
      </li>
    {% endif %}

    <li class="page-item active">
      <a class="page-link shadow-lg bg-gradient-primary cursor-pointer">{{ page_obj.number }} of {{ paginator.num_pages }}</a>
    </li>

    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.next_page_number %}" class="page-link shadow-lg">next</a>
      </li>
    {% endif %}

  </ul>
{% endif %}

templates/includes/scripts.html
  <script src="/static/assets/js/core/popper.min.js" type="text/javascript"></script>
  <script src="/static/assets/js/core/bootstrap.min.js" type="text/javascript"></script>
  <script src="/static/assets/js/plugins/perfect-scrollbar.min.js"></script>
  <script src="/static/assets/js/plugins/prism.min.js"></script>
  <script src="/static/assets/js/plugins/parallax.min.js"></script>