kitchen/urls.py
from django.urls import path

from kitchen.views import (
    IndexView,
    IngredientListView,
    IngredientCreateView,
    IngredientDeleteView,
    DishTypeListView,
    DishTypeCreateView,
    DishTypeDeleteView,
    DishListView,
    DishDetailView,
    DishCreateView,
    DishUpdateView,
    DishDeleteView,
    DishTypeUpdateView,
    CookListView,
    CookDetailView,
    CookCreateView,
    CookUpdateView,
    ToggleAssignToDish,
    CookDeleteView,
)

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("ingredient/", IngredientListView.as_view(), name="ingredient-list"),
    path("ingredient/create/", IngredientCreateView.as_view(), name="ingredient-create"),
    path("ingredient/<int:pk>/delete/", IngredientDeleteView.as_view(), name="ingredient-delete"),
    path("dish_type/", DishTypeListView.as_view(), name="dish-type-list"),
    path("dish_type/create/", DishTypeCreateView.as_view(), name="dish-type-create"),
    path("dish_type/<int:pk>/update/", DishTypeUpdateView.as_view(), name="dish-type-update"),
    path("dish_type/<int:pk>/delete", DishTypeDeleteView.as_view(), name="dish-type-delete"),
    path("dish/", DishListView.as_view(), name="dish-list"),
    path("dish/<int:pk>/", DishDetailView.as_view(), name="dish-detail"),
    path("dish/create/", DishCreateView.as_view(), name="dish-create"),
    path("dish/<int:pk>/update/", DishUpdateView.as_view(), name="dish-update"),
    path("dish/<int:pk>/delete/", DishDeleteView.as_view(), name="dish-delete"),
    path("dishes/<int:pk>/toggle-assign/", ToggleAssignToDish.as_view(), name="toggle-dish-assign",),
    path("cook/", CookListView.as_view(), name="cook-list"),
    path("cook/<int:pk>/", CookDetailView.as_view(), name="cook-detail"),
    path("cook/create/", CookCreateView.as_view(), name="cook-create"),
    path("cook/<int:pk>/update/", CookUpdateView.as_view(), name="cook-update"),
    path("cook/<int:pk>/delete/", CookDeleteView.as_view(), name="cook-delete"),
]

app_name = "kitchen"

restaurant/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("kitchen.urls", namespace="kitchen")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

kitchen/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models


class DishType(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class Ingredient(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class Cook(AbstractUser):
    years_of_experience = models.IntegerField(default=0)

    class Meta:
        ordering = ["username"]

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class Dish(models.Model):
    name = models.CharField(max_length=60)
    description = models.TextField(max_length=500)
    price = models.DecimalField(max_digits=7, decimal_places=2)
    dish_type = models.ForeignKey(
        DishType,
        on_delete=models.CASCADE,
        related_name="dishes"
    )
    cooks = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="dishes")
    ingredients = models.ManyToManyField(Ingredient, related_name="dishes")

    def __str__(self):
        return self.name

kitchen/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

from kitchen.models import DishType, Dish, Ingredient, Cook


class DishTypeForm(forms.ModelForm):
    name = forms.CharField(
        widget=forms.TextInput(attrs={"placeholder": "Enter the type of dish here"})
    )

    class Meta:
        model = DishType
        fields = "__all__"


class DishForm(forms.ModelForm):
    cooks = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )

    class Meta:
        model = Dish
        fields = "__all__"


class CookForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = Cook
        fields = UserCreationForm.Meta.fields + (
            "first_name",
            "last_name",
            "years_of_experience",
        )


class IngredientSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by name..."})
    )


class DishTypeSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by name..."})
    )


class DishSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by name..."})
    )


class CookSearchForm(forms.Form):
    username = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by username..."})
    )

kitchen/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from kitchen.forms import DishTypeForm, DishForm, CookForm, IngredientSearchForm, DishTypeSearchForm, \
    DishSearchForm, CookSearchForm
from kitchen.models import Cook, Dish, DishType, Ingredient


class IndexView(generic.TemplateView):
    template_name = "kitchen/index.html"

    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)
        context["num_dish"] = Dish.objects.count()
        context["num_cooks"] = Cook.objects.count()
        context["num_dish_types"] = DishType.objects.count()
        context["num_ingredients"] = Ingredient.objects.count()
        context['num_visits'] = self.request.session['num_visits']

        return context

    def get(self, request, *args, **kwargs):
        num_visits = request.session.get('num_visits', 0)
        request.session['num_visits'] = num_visits + 1
        return super().get(request, *args, **kwargs)


class IngredientListView(LoginRequiredMixin, generic.ListView):
    model = Ingredient
    paginate_by = 5
    template_name = "kitchen/ingredient_list.html"

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(IngredientListView, self).get_context_data(**kwargs)

        name = self.request.GET.get("name", "")

        context["search_forms"] = IngredientSearchForm(initial={
            "name": name
        })

        return context

    def get_queryset(self):
        queryset = Ingredient.objects.all()
        form = IngredientSearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(
                name__icontains=form.cleaned_data["name"]
            )

        return queryset


class IngredientCreateView(LoginRequiredMixin, generic.CreateView):
    model = Ingredient
    fields = "__all__"
    success_url = reverse_lazy("kitchen:ingredient-list")


class IngredientDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Ingredient
    success_url = reverse_lazy("kitchen:ingredient-list")


class DishTypeListView(LoginRequiredMixin, generic.ListView):
    model = DishType
    paginate_by = 5
    context_object_name = "dish_type_list"
    template_name = "kitchen/dish_type_list.html"

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(DishTypeListView, self).get_context_data(**kwargs)

        name = self.request.GET.get("name", "")

        context["search_forms"] = DishTypeSearchForm(initial={
            "name": name
        })

        return context

    def get_queryset(self):
        queryset = DishType.objects.all()
        form = DishTypeSearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(
                name__icontains=form.cleaned_data["name"]
            )

        return queryset


class DishTypeCreateView(LoginRequiredMixin, generic.CreateView):
    model = DishType
    form_class = DishTypeForm
    template_name = "kitchen/dish_type_form.html"
    success_url = reverse_lazy("kitchen:dish-type-list")


class DishTypeUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = DishType
    fields = "__all__"
    template_name = "kitchen/dish_type_form.html"
    success_url = reverse_lazy("kitchen:dish-type-list")


class DishTypeDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = DishType
    template_name = "kitchen/dish_type_confirm_delete.html"
    success_url = reverse_lazy("kitchen:dish-type-list")


class DishListView(LoginRequiredMixin, generic.ListView):
    model = Dish
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(DishListView, self).get_context_data(**kwargs)

        name = self.request.GET.get("name", "")

        context["search_forms"] = DishSearchForm(initial={
            "name": name
        })

        return context

    def get_queryset(self):
        queryset = Dish.objects.select_related("dish_type")
        form = DishSearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(
                name__icontains=form.cleaned_data["name"]
            )

        return queryset


class DishDetailView(LoginRequiredMixin, generic.DetailView):
    model = Dish


class DishUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Dish
    form_class = DishForm
    success_url = reverse_lazy("kitchen:dish-list")


class DishDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Dish
    form_class = DishForm


class DishCreateView(LoginRequiredMixin, generic.CreateView):
    model = Dish
    form_class = DishForm
    success_url = reverse_lazy("kitchen:dish-list")


class CookListView(LoginRequiredMixin, generic.ListView):
    model = Cook
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(CookListView, self).get_context_data(**kwargs)

        username = self.request.GET.get("username", "")

        context["search_forms"] = CookSearchForm(initial={
            "username": username
        })

        return context

    def get_queryset(self):
        queryset = Cook.objects.all()
        form = CookSearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(
                username__icontains=form.cleaned_data["username"]
            )

        return queryset


class CookDetailView(LoginRequiredMixin, generic.DetailView):
    model = Cook


class CookCreateView(LoginRequiredMixin, generic.CreateView):
    model = Cook
    form_class = CookForm
    success_url = reverse_lazy("kitchen:cook-list")


class CookUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Cook
    form_class = CookForm
    success_url = reverse_lazy("kitchen:cook-detail")


class CookDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Cook
    success_url = reverse_lazy("kitchen:cook-list")


class ToggleAssignToDish(LoginRequiredMixin, generic.View):
    def post(self, request, pk):
        dish = Dish.objects.get(pk=pk)
        cook = Cook.objects.get(pk=self.request.user.id)
        if dish in cook.dishes.all():
            cook.dishes.remove(dish)
        else:
            cook.dishes.add(dish)
        return HttpResponseRedirect(
            reverse_lazy("kitchen:dish-detail", kwargs={"pk": self.kwargs["pk"]})
        )

templates/kitchen/cook_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <div class="page-header section-height-100 py-7 px-8 shadow-lg" style="background-image: url('/static/assets/img/curved-images/stock-photo-fresh-vegetables-lying-in-row.jpg')">
    <div class="pt-4 px-5 border-radius-2xl section-height-85 col-lg-12 blur shadow-blur">

      <div class="border-radius-xl blur-section px-4 pt-3 pb-1 my-3 text-dark">
        <h3 class="font-weight-bold">Are you sure you want to delete <strong>{{ cook.username }}</strong>?</h3>
        <form action="" method="post">
          {% csrf_token %}

          <input type="submit" value="Yes, I am" class="btn bg-gradient-danger">
          <a href="{% url 'kitchen:cook-detail' pk=user.id %}" class="btn btn-secondary">
            Cancel
          </a>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

templates/kitchen/cook_detail.html
{% extends "base.html" %}

{% block content %}
  <div class="page-header section-height-100 py-7 px-8 shadow-lg" style="background-image: url('/static/assets/img/curved-images/stock-photo-fresh-vegetables-lying-in-row.jpg')">
    <div class="pt-4 px-5 border-radius-2xl section-height-85 col-lg-12 blur shadow-blur">
      <h2>
        {{ cook.first_name }} {{ cook.last_name }}
        {% if user == cook %} <span class="text-muted">(Me)</span>
          <a href="{% url 'kitchen:cook-delete' pk=user.id %}" class="btn my-auto bg-gradient-danger float-end">
            Delete account
          </a>
          <a href="{% url 'kitchen:cook-update' pk=user.id %}" class="btn my-auto btn-secondary float-end">
            Update profile
          </a>
        {% endif %}
      </h2>
      <div class="border-radius-xl blur-section px-4 pt-3 pb-1 my-3">
        <p class="text-dark"><strong>Username:</strong> {{ cook.username }}</p>
        <p class="text-dark"><strong>Years of experience:</strong> {{ cook.years_of_experience }}</p>
      </div>

      <div class="border-radius-xl blur-section px-4 pt-3 pb-1">
        <h4>Dishes that the cook prepares</h4>
        <ul>
          {% for dish in cook.dishes.all %}
            <li><a class="text-gradient text-primary" href="{% url 'kitchen:dish-detail' pk=dish.id%}">{{ dish.name }}</a></li>
          {% empty %}
            <li>There are no dishes here.</li>
          {% endfor %}
        </ul>
      </div>

    </div>
  </div>
{% endblock %}

templates/kitchen/cook_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="page-header section-height-100 py-7 px-12 shadow-lg" style="background-image: url('/static/assets/img/curved-images/stock-photo-fresh-vegetables-lying-in-row.jpg')">
    <div class="pt-4 px-5 border-radius-2xl section-height-85 col-lg-9 blur shadow-blur">
      <h2>
        {{ object|yesno:"Update,Create" }} Cook
        <a href="{% url 'kitchen:cook-detail' pk=user.id %}" class="btn btn-secondary my-auto float-end">
          Cancel
        </a>
      </h2>
      <form action="" method="post" novalidate>
        {% csrf_token %}
        {{ form|crispy }}

        <input type="submit" value="Submit" class="btn btn-primary">
      </form>
    </div>
  </div>
{% endblock %}

templates/kitchen/cook_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="page-header section-height-100 py-7 px-8 shadow-lg" style="background-image: url('/static/assets/img/curved-images/stock-photo-fresh-vegetables-lying-in-row.jpg')">
    <div class="pt-4 px-5 border-radius-2xl section-height-85 col-lg-12 blur shadow-blur">
      <h2>
        Cook List
        <a href="{% url 'kitchen:cook-create' %}" class="btn bg-gradient-primary my-auto float-end shadow-lg">
          Create cook
        </a>
      </h2>
      <form action="" method="get" class="form-inline">
        {{ search_forms|crispy }}
        <input type="submit" value="Search" class="btn btn-secondary">
      </form>
      {% if cook_list %}
      <table class="table">
        <tr>
          <th>ID</th>
          <th>Username</th>
          <th>First name</th>
          <th>Last name</th>
          <th>Year of experience</th>
        </tr>
      {% for cook in cook_list %}
        <tr>
          <td>{{ cook.id }}</td>
          <td><a class="text-primary text-gradient" href="{% url 'kitchen:cook-detail' pk=cook.id %}">{{ cook.username }}{% if user == cook %} (Me){% endif %}</a></td>
          <td>{{ cook.first_name }}</td>
          <td>{{ cook.last_name }}</td>
          <td>{{ cook.years_of_experience }}</td>
        </tr>
      {% endfor %}

      </table>
      {% else %}
        <p>There are no drivers in the service.</p>
      {% endif %}
    </div>
  </div>
{% endblock %}

templates/kitchen/dish_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <div class="page-header section-height-100 py-7 px-8 shadow-lg" style="background-image: url('/static/assets/img/curved-images/stock-photo-fresh-vegetables-lying-in-row.jpg')">
    <div class="pt-4 px-5 border-radius-2xl section-height-85 col-lg-12 blur shadow-blur">

      <div class="border-radius-xl blur-section px-4 pt-3 pb-1 my-3 text-dark">
        <h3 class="font-weight-bold">Are you sure you want to delete <strong>{{ dish }}</strong>?</h3>
        <form action="" method="post">
          {% csrf_token %}

          <input type="submit" value="Yes, I am" class="btn bg-gradient-danger">
          <a href="{% url 'kitchen:dish-list' %}" class="btn btn-secondary">
            Cancel
          </a>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

templates/kitchen/dish_detail.html
{% extends "base.html" %}

{% block content %}
  <div class="page-header section-height-100 py-7 px-8 shadow-lg" style="background-image: url('/static/assets/img/curved-images/stock-photo-fresh-vegetables-lying-in-row.jpg')">
    <div class="pt-4 px-5 border-radius-2xl section-height-85 col-lg-12 blur shadow-blur">
      <h2>
        {{ dish.name }}
        <a href="{% url 'kitchen:dish-delete' pk=dish.id %}" class="btn bg-gradient-danger my-auto float-end">
          Delete
        </a>
        <a href="{% url 'kitchen:dish-update' pk=dish.id %}" class="btn btn-secondary my-auto float-end">
          Update
        </a>
      </h2>
      <div class="border-radius-xl blur-section px-4 pt-3 pb-1 my-3 text-dark">
        <p>
          <strong>Dish Type:</strong>
          {{ dish.dish_type }}
        </p>
        <p><strong>Price:</strong> {{ dish.price }}</p>
      </div>
      <div class="border-radius-xl blur-section px-4 pt-3 pb-1 my-3">
        <h5>Description</h5>
        <p>{{ dish.description }}</p>
      </div>
      <div class="border-radius-xl blur-section px-4 pt-3 pb-1 my-3">
        <h5>
          Cooks
          {% if dish in user.dishes.all %}
          <form action="{% url 'kitchen:toggle-dish-assign' pk=dish.id %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn bg-gradient-danger float-end my-auto">
              Delete me from this dish
            </button>
          </form>
          {% else %}
          <form action="{% url 'kitchen:toggle-dish-assign' pk=dish.id %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn bg-gradient-success float-end my-auto">
              Assign me to this dish
            </button>
          </form>
          {% endif %}
        </h5>
        <ul>
          {% for cook in dish.cooks.all %}
            <li><a class="text-primary text-gradient" href="{% url 'kitchen:cook-detail' pk=cook.id%}">{{ cook.username }} ({{ cook.first_name }} {{ cook.last_name }}) {% if user == cook %} (Me){% endif %}</a></li>
          {% empty %}
            <li>There are no cooks here.</li>
          {% endfor %}
        </ul>
      </div>
      <div class="border-radius-xl blur-section px-4 pt-3 pb-1 my-3">
        <h5>
        Ingredients
        </h5>
        <ul>
          {% for ingredient in dish.ingredients.all %}
            <li>{{ ingredient.name }}</li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>
{% endblock %}

templates/kitchen/dish_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="page-header section-height-100 py-7 px-12 shadow-lg" style="background-image: url('/static/assets/img/curved-images/stock-photo-fresh-vegetables-lying-in-row.jpg')">
    <div class="pt-4 px-5 border-radius-2xl section-height-85 col-lg-9 blur shadow-blur">
      <h2>
        {{ object|yesno:"Update,Create" }} dish
        {% if object %}
          <a href="{% url 'kitchen:dish-detail' pk=dish.id %}" class="btn btn-secondary my-auto float-end">
            Cancel
          </a>
        {% else %}
          <a href="{% url 'kitchen:dish-list' %}" class="btn btn-secondary my-auto float-end">
            Cancel
          </a>
        {% endif %}
      </h2>
      <form action="" method="post" novalidate>
        {% csrf_token %}
        {{ form|crispy }}

        <input type="submit" value="Submit" class="btn btn-primary">
      </form>
    </div>
  </div>
{% endblock %}

templates/kitchen/dish_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="page-header section-height-100 py-7 px-8 shadow-lg" style="background-image: url('/static/assets/img/curved-images/stock-photo-fresh-vegetables-lying-in-row.jpg')">
    <div class="pt-4 px-5 border-radius-2xl section-height-85 col-lg-12 blur shadow-blur">
      <h2>
        Dishes
        <a href="{% url 'kitchen:dish-create' %}" class="btn btn-outline-primary my-auto float-end">
          Create dish
        </a>
      </h2>
      {% if dish_list %}
        <form action="" method="get" class="form-inline">
          {{ search_forms|crispy }}
          <input type="submit" value="Search" class="btn btn-secondary">
        </form>
        <table class="table table-bordered table-hover shadow-lg bg-white">
          <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Price</th>
            <th>Dish Type</th>
          </tr>

          {% for dish in dish_list %}
            <tr>
              <td>
                  {{ dish.id }}
              </td>
              <td>
                <a class="text-primary text-gradient" href="{% url 'kitchen:dish-detail' pk=dish.id%}">{{ dish.name }}</a>
              </td>
              <td>
                  {{ dish.price }}
              </td>
              <td>
                {{ dish.dish_type }}
              </td>
            </tr>
          {% endfor %}
        </table>

      {% else %}
        <p>There are no dishes in the service.</p>
      {% endif %}
      {% include "includes/pagination.html" %}
    </div>
  </div>
{% endblock %}

templates/kitchen/dish_type_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <div class="page-header section-height-100 py-7 px-8 shadow-lg" style="background-image: url('/static/assets/img/curved-images/stock-photo-fresh-vegetables-lying-in-row.jpg')">
    <div class="pt-4 px-5 border-radius-2xl section-height-85 col-lg-12 blur shadow-blur">

      <div class="border-radius-xl blur-section px-4 pt-3 pb-1 my-3 text-dark">
        <h3 class="font-weight-bold">Are you sure you want to delete <strong>{{ dishtype }}</strong>?</h3>
        <p class="font-weight-bold"><i>All Dishes with this dish type will be also deleted!</i></p>
        <form action="" method="post">
          {% csrf_token %}

          <input type="submit" value="Yes, I am" class="btn bg-gradient-danger">
          <a href="{% url 'kitchen:dish-type-list' %}" class="btn btn-secondary">
            Cancel
          </a>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

templates/kitchen/dish_type_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="page-header section-height-100 py-7 px-12 shadow-lg" style="background-image: url('/static/assets/img/curved-images/stock-photo-fresh-vegetables-lying-in-row.jpg')">
    <div class="pt-4 px-5 border-radius-2xl section-height-85 col-lg-9 blur shadow-blur">
      <h1>{{ object|yesno:"Update, Create" }} type of dish</h1>
      <form action="" method="post" novalidate>
        {% csrf_token %}
        {{ form|crispy }}

        <input type="submit" value="Submit" class="btn btn-primary">
        <a href="{% url 'kitchen:dish-type-list' %}" class="btn btn-secondary my-auto float-end">
            Cancel
        </a>
      </form>
    </div>
  </div>
{% endblock %}

templates/kitchen/dish_type_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="page-header section-height-100 py-7 px-8 shadow-lg" style="background-image: url('/static/assets/img/curved-images/stock-photo-fresh-vegetables-lying-in-row.jpg')">
    <div class="pt-4 px-5 border-radius-2xl section-height-85 col-lg-12 blur shadow-blur">
      <h2>
        Dish Types
        <a href="{% url 'kitchen:dish-type-create' %}" class="btn bg-gradient-primary my-auto float-end shadow-lg">
          Add DishType
        </a>
      </h2>

      {% if dish_type_list %}
        <form action="" method="get" class="form-inline">
          {{ search_forms|crispy }}
          <input type="submit" value="Search" class="btn btn-secondary">
        </form>
        <table class="table table-bordered table-hover shadow-lg bg-white">
          <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Update</th>
            <th>Delete</th>
          </tr>

          {% for dish_type in dish_type_list %}
            <tr>
              <td>
                {{ dish_type.id }}
              </td>
              <td>
              {{ dish_type.name }}
              </td>
              <td>
                <a href="{% url 'kitchen:dish-type-update' pk=dish_type.id %}">
                  Update
                </a>
              </td>
              <td>
                <a href="{% url 'kitchen:dish-type-delete' pk=dish_type.id %}">
                  Delete
                </a>
              </td>
            </tr>
          {% endfor %}
        </table>

      {% else %}
          <p>There are no dish types in the service.</p>
      {% endif %}
      {% include "includes/pagination.html" %}
    </div>
  </div>
{% endblock %}

templates/kitchen/ingredient_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="page-header section-height-100 py-7 px-8 shadow-lg" style="background-image: url('/static/assets/img/curved-images/stock-photo-fresh-vegetables-lying-in-row.jpg')">
    <div class="pt-4 px-5 border-radius-2xl section-height-85 col-lg-12 blur shadow-blur">
      <h2>
        Ingredients
        <a href="{% url 'kitchen:ingredient-create' %}" class="btn bg-gradient-primary my-auto float-end shadow-lg">
          Add ingredient
        </a>
      </h2>

      {% if ingredient_list %}
        <form action="" method="get" class="form-inline">
          {{ search_forms|crispy }}
          <input type="submit" value="Search" class="btn btn-secondary">
        </form>
        <table class="table table-bordered table-hover shadow-lg bg-white">
          <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Delete</th>
          </tr>

          {% for ingredien in ingredient_list %}
            <tr>
              <td>
                {{ ingredien.id }}
              </td>
              <td>
                {{ ingredien.name }}
              </td>
              <td>
                <a href="{% url 'kitchen:ingredient-delete' pk=ingredien.id %}">
                  Delete
                </a>
              </td>
            </tr>
          {% endfor %}
        </table>

      {% else %}
          <p>There are no ingredients in the service.</p>
      {% endif %}
      {% include "includes/pagination.html" %}
    </div>
  </div>
{% endblock %}